# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
# config/services.yaml
parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Injection automatique du client Guzzle
    GuzzleHttp\Client: ~

    # Configuration spécifique pour le service ZohoSignService
    App\Service\ZohoSignService:
        arguments:
            $clientId: '%env(ZOHO_CLIENT_ID)%'
            $clientSecret: '%env(ZOHO_CLIENT_SECRET)%'
            $redirectUri: '%env(ZOHO_REDIRECT_URI)%'
            $refreshToken: '%env(ZOHO_REFRESH_TOKEN)%'
